const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
  await ctx.addInitScript(() => { localStorage.setItem("tourDone", "1"); localStorage.setItem("guestStarted", "1"); new MutationObserver(() => document.querySelectorAll(".tour-dlg").forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => { window.__noCelebrate = 1; new MutationObserver(() => document.querySelectorAll('.celebrate:not(.wish-dlg)').forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  await p.goto(U + '#/new/cloud'); await p.waitForTimeout(500);
  await p.fill('#f-title', '又遲到了'); await p.click('#save'); await p.waitForTimeout(600);
  await p.fill('#rf-text', '後來想想他那天很累'); await p.click('#rf-add'); await p.waitForTimeout(500);
  await p.fill('#rf-date', '2026-09-20'); await p.fill('#rf-text', '更早的反思'); await p.click('#rf-add'); await p.waitForTimeout(500);
  console.log('reflections', await p.$$eval('.tl-body .prose', (e) => e.map((x) => x.textContent)));
  await p.screenshot({ path: 'rf1.png', fullPage: true });
  await p.click('[data-del-rf]'); await p.waitForTimeout(500);
  console.log('after delete', await p.$$eval('.tl-body .prose', (e) => e.map((x) => x.textContent)));
  await p.goto(U + '#/list/cloud'); await p.waitForTimeout(500);
  console.log('tile hint', await p.isVisible('text=1 則反思'));
  console.log('errors', errs); await b.close();
})();
