// 單人版（沒填雲端設定）煙霧測試
const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, acceptDownloads: true });
  await ctx.addInitScript(() => { localStorage.setItem("tourDone", "1"); localStorage.setItem("guestStarted", "1"); new MutationObserver(() => document.querySelectorAll(".tour-dlg").forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  await ctx.route('**/js/config.js', (r) => r.fulfill({ contentType: 'text/javascript', body: "window.APP_CONFIG={SUPABASE_URL:'',SUPABASE_ANON_KEY:''};" }));
  await ctx.addInitScript(() => { window.__noCelebrate = 1; new MutationObserver(() => document.querySelectorAll('.celebrate:not(.wish-dlg)').forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  const log = (...a) => console.log(...a);
  await p.goto(U + '#/'); await p.waitForTimeout(600);
  await p.goto(U + '#/new/happy'); await p.waitForTimeout(400);
  await p.fill('#f-title', '單人一'); await p.setInputFiles('#f-photos', 'big.jpg'); await p.waitForTimeout(700); await p.click('#save'); await p.waitForTimeout(700);
  const id = p.url().split('/').pop();
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(600);
  log('tile img', await p.$$eval('.tile-img', (e) => e.length));
  await p.goto(U + '#/view/' + id); await p.waitForTimeout(400); await p.click('#delete'); await p.waitForTimeout(600);
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  log('trash', await p.isVisible('text=最近刪除（1）'));
  await p.click('[data-restore]'); await p.waitForTimeout(600);
  const [dl] = await Promise.all([p.waitForEvent('download'), p.click('#export')]); await p.waitForTimeout(400);
  log('backup toast', await p.textContent('#toast'));
  await p.click('#export-read'); await p.waitForTimeout(1200);
  log('read has', (await p.evaluate(() => document.querySelector('.read-body').shadowRoot.innerHTML)).includes('單人一')); await p.click('#read-close');
  log('no delete-account', !(await p.isVisible('#delete-account')));
  console.log('errors', errs); await b.close();
})();
