const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.addInitScript(() => { localStorage.setItem("tourDone", "1"); localStorage.setItem("pushAsk", JSON.stringify({ n: 3, at: 0 })); localStorage.setItem("guestStarted", "1"); new MutationObserver(() => document.querySelectorAll(".tour-dlg").forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => localStorage.setItem('mockAutoApprove', '1'));
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  const log = (...a) => console.log(...a);
  const as = async (uid, hash) => { await p.evaluate((u) => (u ? sessionStorage.setItem('mockUid', u) : sessionStorage.removeItem('mockUid')), uid); await p.goto(U + hash); await p.reload(); await p.waitForTimeout(800); };
  await p.goto(U + '#/login'); await p.waitForTimeout(500);
  await p.fill('#email', 'jas@x.com'); await p.fill('#password', 'secret123'); await p.click('#login-btn'); await p.waitForTimeout(800);
  await p.evaluate(async () => {
    await DB.setSetting('names', { me: 'Jasmine', partner: '小明' });
    const base = { emojis: [], tags: [], date: '2026-09-01', createdAt: 1, updatedAt: 1, photoIds: [], visibility: 'shared' };
    await DB.putRecord({ ...base, id: 'h1', no: 1, type: 'happy', title: '看海' });
    await DB.putRecord({ ...base, id: 'f1', no: 1, type: 'fight', title: '家事', category: '生活', status: 'open', followUps: [] });
    await DB.putRecord({ ...base, id: 'h2', no: 2, type: 'happy', title: '祕密', visibility: 'locked' });
  });
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  await p.fill('#s-name', 'Jasmine'); await p.fill('#s-pass', '123456'); await p.click('#s-create'); await p.waitForTimeout(600);
  const code = (await p.textContent('.share-code')).trim();
  await as(null, '#/login'); await p.click('text=我是另一半，用分享碼加入'); await p.waitForTimeout(300);
  await p.fill('#j-code', code); await p.fill('#j-pass', '123456'); await p.fill('#j-name', '小明'); await p.click('#join-btn'); await p.waitForTimeout(900);
  const a1 = await p.evaluate(() => sessionStorage.getItem('mockUid'));
  await p.goto(U + '#/view/h1'); await p.waitForTimeout(700);
  await p.click('#heart-btn'); await p.waitForTimeout(700);
  log('partner hearted', await p.textContent('#heart-btn'));
  log('cannot heart locked', await p.evaluate(async () => { try { await CloudDB.toggleHeart('h2'); return 'no!'; } catch (e) { return e.message; } }));
  await p.goto(U + '#/view/f1'); await p.waitForTimeout(700);
  await p.fill('#pn-text', '我那天其實很累<b>x</b>'); await p.click('#pn-add'); await p.waitForTimeout(700);
  log('partner note shown', await p.isVisible('text=我那天其實很累<b>x</b>'));
  await p.screenshot({ path: 'n1-partner-fight.png', fullPage: true });
  await as('owner-jas', '#/view/h1');
  log('owner sees heart', await p.isVisible('text=小明 按了愛心'));
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(700);
  log('owner tile heart', await p.isVisible('text=小明按了愛心'));
  await p.goto(U + '#/view/f1'); await p.waitForTimeout(700);
  log('owner sees note', await p.isVisible('text=小明的補充'), await p.isVisible('text=我那天其實很累<b>x</b>'), 'no textarea', !(await p.isVisible('#pn-text')));
  await p.screenshot({ path: 'n2-owner-fight.png', fullPage: true });
  await as(a1, '#/view/h1'); await p.click('#heart-btn'); await p.waitForTimeout(700);
  log('unhearted', await p.textContent('#heart-btn'));
  await p.goto(U + '#/view/f1'); await p.waitForTimeout(700); await p.click('[data-del-pn]'); await p.waitForTimeout(700);
  log('note deleted', !(await p.isVisible('text=我那天其實很累')));
  console.log('errors', errs); await b.close();
})();
