const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.addInitScript(() => { localStorage.setItem("tourDone", "1"); localStorage.setItem("guestStarted", "1"); new MutationObserver(() => document.querySelectorAll(".tour-dlg").forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => localStorage.setItem('mockAutoApprove', '1'));
  await ctx.addInitScript(() => { new MutationObserver(() => document.querySelectorAll('.celebrate:not(.wish-dlg)').forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  const log = (...a) => console.log(...a);
  const as = async (uid, hash) => { await p.evaluate((u) => (u ? sessionStorage.setItem('mockUid', u) : sessionStorage.removeItem('mockUid')), uid); await p.goto(U + hash); await p.reload(); await p.waitForTimeout(800); };
  await p.goto(U + '#/login'); await p.waitForTimeout(500);
  await p.fill('#email', 'jas@x.com'); await p.fill('#password', 'secret123'); await p.click('#login-btn'); await p.waitForTimeout(800);
  await p.evaluate(async () => {
    await DB.setSetting('names', { me: 'Jasmine', partner: '小明' });
    const base = { emojis: [], tags: [], createdAt: 1, updatedAt: 1, photoIds: [] };
    await DB.putRecord({ ...base, id: 'h1', no: 1, type: 'happy', title: '看海', date: '2026-09-01', visibility: 'shared' });
    await DB.putRecord({ ...base, id: 'c1', no: 1, type: 'cloud', title: '主人的祕密烏雲', date: '2026-09-02', visibility: 'locked', reflections: [] });
  });
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  await p.fill('#s-name', 'Jasmine'); await p.fill('#s-pass', '123456'); await p.click('#s-create'); await p.waitForTimeout(600);
  const code = (await p.textContent('.share-code')).trim();
  await as(null, '#/login'); await p.click('text=我是另一半，用分享碼加入'); await p.waitForTimeout(300);
  await p.fill('#j-code', code); await p.fill('#j-pass', '123456'); await p.fill('#j-name', '小明'); await p.click('#join-btn'); await p.waitForTimeout(900);
  const pid = await p.evaluate(() => sessionStorage.getItem('mockUid'));
  log('P unbound tabbar has tasks', await p.isVisible('.tabbar >> text=任務'));
  await p.goto(U + '#/new/happy'); await p.waitForTimeout(500);
  log('P unbound new -> bind', p.url().endsWith('#/bind'));
  await p.evaluate((id) => { const S = JSON.parse(localStorage.mockServer); S.users[id].is_anonymous = false; S.users[id].email = 'ming@x.com'; localStorage.mockServer = JSON.stringify(S); }, pid);
  await p.goto(U + '#/'); await p.reload(); await p.waitForTimeout(800);
  log('P bound: FAB', await p.isVisible('.tab-add'), 'title', await p.textContent('h1'));
  // 另一半寫一則美好（分享）、一則烏雲（預設上鎖）
  await p.click('.tab-add'); await p.waitForTimeout(600);
  log('P form type seg', await p.isVisible('[data-type]'), 'vis opts', await p.$$eval('[data-vis]', (e) => e.map((x) => x.dataset.vis)));
  await p.fill('#f-title', '他煮了晚餐'); await p.fill('#f-desc', '好吃'); await p.click('#save'); await p.waitForTimeout(900);
  const ph = p.url().split('/view/')[1];
  log('P happy saved', !!ph, await p.isVisible('text=你新增的'), 'no', await p.evaluate(async (id) => (await DB.getRecord(id)).no, ph));
  await p.goto(U + '#/new/cloud'); await p.waitForTimeout(600);
  log('P cloud default', await p.textContent('[data-vis].on'));
  await p.fill('#f-title', '她又遲到'); await p.click('#save'); await p.waitForTimeout(900);
  const pc = p.url().split('/view/')[1];
  await p.fill('#rf-text', '其實也還好'); await p.click('#rf-add'); await p.waitForTimeout(700);
  await p.click('#clear-btn'); await p.waitForTimeout(700);
  log('P cloud reflect+clear', await p.evaluate(async (id) => { const r = await DB.getRecord(id); return [r.reflections.length, !!r.clearedAt, r.visibility]; }, pc));
  await p.click('#clear-btn'); await p.waitForTimeout(700);
  log('P uncleared', await p.evaluate(async (id) => !(await DB.getRecord(id)).clearedAt, pc));
  await p.goto(U + '#/view/h1'); await p.waitForTimeout(600);
  log('P owner happy: no edit', !(await p.isVisible('a:has-text("編輯")')), 'heart btn', await p.isVisible('#heart-btn'));
  await p.goto(U + '#/list/cloud'); await p.waitForTimeout(700);
  log('P cloud list: chips', await p.isVisible('[data-who="mine"]'), 'locked placeholder', await p.isVisible('text=Jasmine還沒有打開這一則'), 'own', await p.isVisible('text=她又遲到'));
  await p.click('[data-who="mine"]'); await p.waitForTimeout(500);
  log('P mine filter hides placeholder', !(await p.isVisible('text=Jasmine還沒有打開這一則')));
  await p.screenshot({ path: 'd1-partner-list.png', fullPage: true });
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(600);
  await p.click('[data-who="all"]').catch(() => {}); await p.waitForTimeout(400);
  log('P happy count', await p.textContent('.topbar .count'));
  // 主人那邊
  await as('owner-jas', '#/');
  log('O home happy count', await p.textContent('a[href="#/list/happy"] .count').catch(() => '?'));
  await p.goto(U + '#/list/cloud'); await p.waitForTimeout(700);
  log('O sees partner locked placeholder', await p.isVisible('text=小明還沒有打開這一則'), 'no leak', !(await p.isVisible('text=她又遲到')));
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(700);
  log('O sees partner happy', await p.isVisible('text=他煮了晚餐'), await p.isVisible('text=小明寫的'));
  await p.screenshot({ path: 'd2-owner-list.png', fullPage: true });
  await p.goto(U + '#/view/' + ph); await p.waitForTimeout(700);
  log('O partner happy: no edit', !(await p.isVisible('a:has-text("編輯")')), 'no delete', !(await p.isVisible('#delete')), await p.isVisible('text=只有小明能修改和刪除'));
  await p.click('#heart-btn'); await p.waitForTimeout(700);
  log('O hearted partner happy', await p.textContent('#heart-btn'));
  log('O cannot overwrite', await p.evaluate(async (id) => { try { const r = await DB.getRecord(id); r.title = 'hack'; await DB.putRecord(r); return 'no!'; } catch (e) { return e.message; } }, ph));
  await p.goto(U + '#/edit/' + ph); await p.waitForTimeout(600);
  log('O edit redirected', p.url().includes('/view/'));
  // 主人新增：編號接在另一半後面
  await p.goto(U + '#/new/happy'); await p.waitForTimeout(600);
  await p.fill('#f-title', '主人第二則'); await p.click('#save'); await p.waitForTimeout(900);
  log('O new no', await p.evaluate(async () => (await DB.allRecords()).find((r) => r.title === '主人第二則').no));
  // 重新編號
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  await p.click('#renumber'); await p.waitForTimeout(900);
  log('renumbered', await p.evaluate(() => JSON.parse(localStorage.mockServer).t.records.filter((r) => r.type === 'happy').map((r) => r.data.title + '=' + r.data.no).join(' ')));
  // 另一半看到主人按的愛心
  await as(pid, '#/view/' + ph);
  log('P sees owner heart', await p.isVisible('text=Jasmine 按了愛心'));
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(700);
  log('P tile heart', await p.isVisible('text=Jasmine按了愛心'));
  await p.goto(U + '#/view/' + ph); await p.waitForTimeout(600);
  await p.click('#delete'); await p.waitForTimeout(800);
  log('P deleted own', await p.evaluate((id) => !JSON.parse(localStorage.mockServer).t.records.some((r) => r.id === id), ph));
  console.log('errors', errs); await b.close();
})();
