const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const log = (...a) => console.log(...a);
  const errs = [];
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.addInitScript(() => { localStorage.setItem("tourDone", "1"); localStorage.setItem("guestStarted", "1"); new MutationObserver(() => document.querySelectorAll(".tour-dlg").forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  const p = await ctx.newPage(); p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  await p.goto(U + '#/'); await p.waitForTimeout(700);
  log('home mascot', await p.$$eval('.mascot svg', (e) => e.length));
  await p.screenshot({ path: 'm1-home.png', fullPage: true });
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(500);
  log('empty mascot', await p.isVisible('.empty .mascot'));
  await p.goto(U + '#/list/cloud'); await p.waitForTimeout(500);
  log('cloud mascot', await p.isVisible('[aria-label^="下雨了"]'));
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  await p.click('[data-mside="left"][data-mcolor="蜜桃"]'); await p.waitForTimeout(400);
  await p.click('[data-mside="right"][data-mcolor="抹茶"]'); await p.waitForTimeout(400);
  log('saved', JSON.stringify(await p.evaluate(() => DB.getSetting('mascot'))), 'pressed', await p.getAttribute('[data-mcolor="蜜桃"][data-mside="left"]', 'aria-pressed'));
  const el = await p.$('text=吉祥物顏色'); await el.scrollIntoViewIfNeeded();
  await p.screenshot({ path: 'm2-settings.png' });
  await p.evaluate(async () => { await DB.putRecord({ id: 'c1', no: 1, type: 'cloud', title: '下雨', date: '2026-09-01', emojis: [], tags: [], photoIds: [], visibility: 'locked', reflections: [], createdAt: 1, updatedAt: 1 }); });
  await p.goto(U + '#/view/c1'); await p.waitForTimeout(600);
  await p.click('#clear-btn'); await p.waitForTimeout(500);
  log('clear pop', await p.isVisible('.mascot-pop'));
  await p.screenshot({ path: 'm3-clear.png' });
  await p.waitForTimeout(3000);
  await p.goto(U + '#/'); await p.waitForTimeout(800);
  log('home colors changed', await p.evaluate(() => document.querySelector('.quick-head svg, .mascot-hello svg').outerHTML.includes('#F8C8B4')));
  console.log('errors', errs); await b.close();
})();
