const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.addInitScript(() => { localStorage.setItem("tourDone", "1"); localStorage.setItem("guestStarted", "1"); new MutationObserver(() => document.querySelectorAll(".tour-dlg").forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => localStorage.setItem('mockAutoApprove', '1'));
  await ctx.addInitScript(() => { new MutationObserver(() => document.querySelectorAll('.celebrate:not(.wish-dlg)').forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  const log = (...a) => console.log(...a);
  const as = async (uid, hash) => { await p.evaluate((u) => (u ? sessionStorage.setItem('mockUid', u) : sessionStorage.removeItem('mockUid')), uid); await p.goto(U + hash); await p.reload(); await p.waitForTimeout(800); };
  await p.goto(U + '#/login'); await p.waitForTimeout(500);
  await p.fill('#email', 'jas@x.com'); await p.fill('#password', 'secret123'); await p.click('#login-btn'); await p.waitForTimeout(800);
  await p.evaluate(async () => {
    const base = { emojis: [], tags: [], date: '2026-09-01', createdAt: 1, updatedAt: 1, photoIds: [], reflections: [] };
    await DB.putRecord({ ...base, id: 'h1', no: 1, type: 'happy', title: '看海', visibility: 'shared' });
  });
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  await p.fill('#s-name', 'Jasmine'); await p.fill('#s-pass', '123456'); await p.click('#s-create'); await p.waitForTimeout(600);
  const code = (await p.textContent('.share-code')).trim();
  log('no pause before partner', !(await p.isVisible('#s-pause')));
  await as(null, '#/login'); await p.click('text=我是另一半，用分享碼加入'); await p.waitForTimeout(300);
  await p.fill('#j-code', code); await p.fill('#j-pass', '123456'); await p.fill('#j-name', '小明'); await p.click('#join-btn'); await p.waitForTimeout(900);
  const pid = await p.evaluate(() => sessionStorage.getItem('mockUid'));
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(600);
  log('P sees before', await p.isVisible('text=看海'));
  await as('owner-jas', '#/settings'); await p.waitForTimeout(300);
  await p.click('#s-pause'); await p.waitForTimeout(700);
  log('paused setting', await p.evaluate(() => DB.getSetting('sharePaused')), 'btn', await p.textContent('#s-pause'));
  await (await p.$('#pause-box')).scrollIntoViewIfNeeded(); await p.screenshot({ path: 'r2-pause.png' });
  await as(pid, '#/'); await p.waitForTimeout(300);
  log('P paused note', await p.isVisible('#paused-note'));
  await p.screenshot({ path: 'r3-partner-paused.png' });
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(600);
  log('P hidden', !(await p.isVisible('text=看海')));
  await as('owner-jas', '#/settings'); await p.waitForTimeout(300);
  await p.click('#s-pause'); await p.waitForTimeout(700);
  await as(pid, '#/list/happy'); await p.waitForTimeout(300);
  log('P back', await p.isVisible('text=看海'), 'note gone', !(await p.isVisible('#paused-note')));
  console.log('errors', errs); await b.close();
})();
