const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.addInitScript(() => { localStorage.setItem("tourDone", "1"); localStorage.setItem("guestStarted", "1"); new MutationObserver(() => document.querySelectorAll(".tour-dlg").forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => localStorage.setItem('mockAutoApprove', '1'));
  await ctx.addInitScript(() => { new MutationObserver(() => document.querySelectorAll('.celebrate:not(.wish-dlg)').forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(e.message));
  let promptAnswer = '';
  p.on('dialog', (d) => (d.type() === 'prompt' ? d.accept(promptAnswer) : d.accept()));
  const log = (...a) => console.log(...a);
  const as = async (uid, hash) => { await p.evaluate((u) => (u ? sessionStorage.setItem('mockUid', u) : sessionStorage.removeItem('mockUid')), uid); await p.goto(U + '#/settings'); await p.reload(); await p.waitForTimeout(500); await p.goto(U + hash); await p.reload(); await p.waitForTimeout(800); };
  await p.goto(U + '#/login'); await p.waitForTimeout(500);
  await p.fill('#email', 'jas@x.com'); await p.fill('#password', 'secret123'); await p.click('#login-btn'); await p.waitForTimeout(800);
  await p.evaluate(async () => { await DB.setSetting('names', { me: 'Jasmine', partner: '小明' }); });
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  await p.fill('#s-name', 'Jasmine'); await p.fill('#s-pass', '123456'); await p.click('#s-create'); await p.waitForTimeout(600);
  const code = (await p.textContent('.share-code')).trim();
  await as(null, '#/login'); await p.click('text=我是另一半，用分享碼加入'); await p.waitForTimeout(300);
  await p.fill('#j-code', code); await p.fill('#j-pass', '123456'); await p.fill('#j-name', '小明'); await p.click('#join-btn'); await p.waitForTimeout(900);
  const pid = await p.evaluate(() => sessionStorage.getItem('mockUid'));
  await p.evaluate((id) => { const S = JSON.parse(localStorage.mockServer); S.users[id].is_anonymous = false; S.users[id].email = 'ming@x.com'; localStorage.mockServer = JSON.stringify(S); }, pid);
  await as('owner-jas', '#/');
  await p.evaluate(async () => {
    const base = { emojis: [], tags: [], date: '2026-09-01', createdAt: 1, updatedAt: 1, photoIds: [], reflections: [] };
    await DB.putRecord({ ...base, id: 'h1', no: 1, type: 'happy', title: '舊的看海', visibility: 'shared' });
    await DB.putRecord({ ...base, id: 'h2', no: 2, type: 'happy', title: '舊的晚餐', visibility: 'shared' });
    await DB.setSetting('names', { me: 'Jasmine', partner: '小明', since: '2020-01-01' });
  });
  await p.goto(U + '#/settings'); await p.waitForTimeout(700);
  log('end card', await p.isVisible('#end-card'));
  await p.goto(U + '#/end'); await p.waitForTimeout(600);
  await p.screenshot({ path: 'r7-end.png', fullPage: true });
  await p.click('#end-archive'); await p.waitForTimeout(1200);
  log('home after archive', p.url().endsWith('#/'), 'count', await p.evaluate(async () => (await DB.allRecords()).length));
  await p.goto(U + '#/settings'); await p.waitForTimeout(700);
  log('archive link', await p.textContent('a[href="#/archive"]').catch(() => null), 'share reset', await p.isVisible('#s-create'));
  await p.goto(U + '#/archive'); await p.waitForTimeout(700);
  log('archive list has', await p.isVisible('text=舊的看海'));
  await p.click('text=舊的看海'); await p.waitForTimeout(700);
  log('archived banner', await p.isVisible('text=封存的紀錄，只有你看得到'), 'no edit', !(await p.isVisible('a:has-text("編輯")')));
  await as(pid, '#/');
  log('old partner kicked', p.url());
  // 新的紀錄編號從 1 開始
  await as('owner-jas', '#/new/happy');
  await p.fill('#f-title', '新的開始'); await p.click('#save'); await p.waitForTimeout(900);
  log('new no', await p.evaluate(async () => (await DB.allRecords()).find((r) => r.title === '新的開始').no));
  // 刪除模式
  await p.goto(U + '#/end'); await p.waitForTimeout(600);
  promptAnswer = '刪除';
  await p.click('#end-delete'); await p.waitForTimeout(1200);
  log('after delete count', await p.evaluate(async () => (await DB.allRecords()).length), 'archive kept', await p.evaluate(async () => (await CloudDB.archivedRecords()).length));
  await p.goto(U + '#/archive'); await p.waitForTimeout(600);
  await p.click('#purge-archive'); await p.waitForTimeout(1000);
  log('archive purged', await p.evaluate(async () => (await CloudDB.archivedRecords()).length));
  console.log('errors', errs); await b.close();
})();
