const { chromium } = require('playwright');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const log = (...a) => console.log(...a);
  const errs = [];
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.addInitScript(() => { localStorage.setItem("tourDone", "1"); localStorage.setItem("guestStarted", "1"); new MutationObserver(() => document.querySelectorAll(".tour-dlg").forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  const p = await ctx.newPage(); p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  const type = async (pin) => { for (const d of pin) await p.click(`.pin-lock [data-pin="${d}"]`); await p.waitForTimeout(500); };
  await p.goto(U + '#/'); await p.waitForTimeout(700);
  log('no lock by default', !(await p.isVisible('.pin-lock')));
  await p.goto(U + '#/settings'); await p.waitForTimeout(700);
  await p.click('#pin-toggle'); await p.waitForTimeout(300);
  await type('1234'); await type('1111');
  log('mismatch keeps pad', await p.isVisible('.pin-lock'));
  await type('1234'); await p.waitForTimeout(500);
  log('saved', await p.evaluate(() => !!localStorage.getItem('appPin')), 'pin card on', await p.textContent('#pin-toggle'));
  await p.reload(); await p.waitForTimeout(900);
  log('locked on open', await p.isVisible('.pin-lock'));
  await p.screenshot({ path: 'r8-pin.png' });
  await type('0000');
  log('wrong stays', await p.isVisible('.pin-lock'), await p.textContent('#pin-sub'));
  await type('1234');
  log('unlocked', !(await p.isVisible('.pin-lock')));
  await p.keyboard.press('Escape');
  await p.goto(U + '#/settings'); await p.waitForTimeout(700);
  await p.click('#pin-toggle'); await p.waitForTimeout(300); await type('1234');
  log('off', await p.evaluate(() => localStorage.getItem('appPin')));
  console.log('errors', errs); await b.close();
})();
