const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.addInitScript(() => { localStorage.setItem("tourDone", "1"); localStorage.setItem("guestStarted", "1"); new MutationObserver(() => document.querySelectorAll(".tour-dlg").forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => { new MutationObserver(() => document.querySelectorAll('.celebrate:not(.wish-dlg)').forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  const p = await ctx.newPage();
  const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  const log = (...a) => console.log(...a);
  const as = async (uid, hash) => { await p.evaluate((u) => (u ? sessionStorage.setItem('mockUid', u) : sessionStorage.removeItem('mockUid')), uid); await p.goto(U + '#/settings'); await p.reload(); await p.waitForTimeout(500); await p.goto(U + hash); await p.reload(); await p.waitForTimeout(800); };
  const join = async (code, name) => { await as(null, '#/login'); await p.click('text=我是另一半，用分享碼加入'); await p.waitForTimeout(300); await p.fill('#j-code', code); await p.fill('#j-pass', '123456'); await p.fill('#j-name', name); await p.click('#join-btn'); await p.waitForTimeout(900); return p.evaluate(() => sessionStorage.getItem('mockUid')); };
  await p.goto(U + '#/login'); await p.waitForTimeout(500);
  await p.fill('#email', 'jas@x.com'); await p.fill('#password', 'secret123'); await p.click('#login-btn'); await p.waitForTimeout(800);
  await p.evaluate(async () => { await DB.putRecord({ id: 'h1', no: 1, type: 'happy', title: '和前任看海', date: '2026-09-01', emojis: [], tags: [], photoIds: [], visibility: 'shared', createdAt: 1, updatedAt: 1 }); });
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  await p.fill('#s-name', 'Jasmine'); await p.fill('#s-pass', '123456'); await p.click('#s-create'); await p.waitForTimeout(600);
  const code = (await p.textContent('.share-code')).trim();
  await p.evaluate(() => localStorage.setItem('mockAutoApprove', '1'));
  await join(code, '小明');
  await p.evaluate(() => localStorage.removeItem('mockAutoApprove'));
  const nid = await join(code, '阿華');
  await as('owner-jas', '#/settings');
  await p.click('[data-approve-partner]'); await p.waitForTimeout(400);
  log('choice shown', await p.isVisible('.choice-dlg'), 'new is primary', await p.getAttribute('[data-choice="new"]', 'class'));
  await p.screenshot({ path: 'r9-choice.png' });
  await p.click('[data-choice="new"]'); await p.waitForTimeout(800);
  log('to end page', p.url().includes('#/end/'), await p.isVisible('text=讓「阿華」加入之前'));
  await p.click('#end-archive'); await p.waitForTimeout(1200);
  log('partners', await p.evaluate(() => JSON.parse(localStorage.mockServer).t.partners.map((x) => x.name + ':' + x.approved).join(',')));
  await as(nid, '#/list/happy');
  log('new partner sees old', await p.isVisible('text=和前任看海'));
  // 同一人換手機：直接取代
  await p.evaluate(() => localStorage.removeItem('mockAutoApprove'));
  const code2 = await p.evaluate(() => JSON.parse(localStorage.mockServer).t.shares[0].code);
  await join(code2, '阿華');
  await as('owner-jas', '#/settings');
  await p.evaluate(async () => { await DB.putRecord({ id: 'h2', no: 1, type: 'happy', title: '新的', date: '2026-09-02', emojis: [], tags: [], photoIds: [], visibility: 'shared', createdAt: 1, updatedAt: 1 }); });
  await p.goto(U + '#/settings'); await p.waitForTimeout(700);
  await p.click('[data-approve-partner]'); await p.waitForTimeout(400);
  log('same is primary', await p.getAttribute('[data-choice="same"]', 'class'));
  await p.click('[data-choice="same"]'); await p.waitForTimeout(800);
  log('replaced', await p.evaluate(() => JSON.parse(localStorage.mockServer).t.partners.map((x) => x.name + ':' + x.approved).join(',')), 'records kept', await p.evaluate(async () => (await DB.allRecords()).length));
  console.log('errors', errs); await b.close();
})();
