const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const log = (...a) => console.log(...a);
  const errs = [];
  // 主人（手機版）
  let ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  let p = await ctx.newPage(); p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  await p.goto(U + '#/'); await p.waitForTimeout(900);
  log('new visitor lands on home', await p.isVisible('.quick-rec'));
  log('owner tour shown', await p.isVisible('.tour-dlg'), await p.textContent('.tour-dlg h2'));
  await p.screenshot({ path: 'r13-tour1.png' });
  await p.click('#tour-next'); await p.waitForTimeout(200);
  log('page2', await p.textContent('.tour-dlg h2'));
  await p.screenshot({ path: 'r14-tour2.png' });
  await p.click('#tour-next'); await p.waitForTimeout(200);
  log('page3', await p.textContent('.tour-dlg h2'));
  await p.click('#tour-next'); await p.waitForTimeout(200);
  log('page4 signup', await p.textContent('.tour-dlg h2'), await p.isVisible('#tour-signup'), await p.textContent('#tour-next'), 'no skip on last', !(await p.isVisible('#tour-skip')));
  await p.screenshot({ path: (process.env.SHOT_DIR || '.') + '/tour-signup.png' });
  await p.click('#tour-next'); await p.waitForTimeout(200);
  log('closed', !(await p.isVisible('.tour-dlg')));
  await p.reload(); await p.waitForTimeout(800);
  log('not again', !(await p.isVisible('.tour-dlg')));
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  await p.click('#tour-again'); await p.waitForTimeout(200);
  log('again from settings', await p.isVisible('.tour-dlg'));
  await p.click('#tour-skip'); await p.waitForTimeout(200);
  log('skip closes', !(await p.isVisible('.tour-dlg')));
  await ctx.close();
  // 有紀錄的舊使用者不跳
  ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  p = await ctx.newPage(); p.on('pageerror', (e) => errs.push(e.message));
  await p.goto(U + '#/new/happy'); await p.waitForTimeout(700);
  await p.evaluate(() => document.querySelectorAll('.tour-dlg').forEach((e) => e.remove()));
  await p.evaluate(() => { localStorage.removeItem('tourDone'); });
  await p.fill('#f-title', '舊的'); await p.click('#save'); await p.waitForTimeout(900);
  await p.goto(U + '#/'); await p.reload(); await p.waitForTimeout(800);
  log('existing user no tour', !(await p.isVisible('.tour-dlg')));
  await ctx.close();
  // 另一半
  ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => localStorage.setItem('mockAutoApprove', '1'));
  await ctx.addInitScript(() => { localStorage.setItem('tourDone', '1'); localStorage.setItem('guestStarted', '1'); });
  p = await ctx.newPage(); p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  await p.goto(U + '#/login'); await p.waitForTimeout(500);
  await p.fill('#email', 'jas@x.com'); await p.fill('#password', 'secret123'); await p.click('#login-btn'); await p.waitForTimeout(800);
  await p.evaluate(async () => { await DB.setSetting('names', { me: 'Jasmine', partner: '小明' }); });
  await p.goto(U + '#/settings'); await p.waitForTimeout(600);
  await p.fill('#s-name', 'Jasmine'); await p.fill('#s-pass', '123456'); await p.click('#s-create'); await p.waitForTimeout(600);
  const code = (await p.textContent('.share-code')).trim();
  await p.evaluate(() => sessionStorage.removeItem('mockUid')); await p.goto(U + '#/login'); await p.reload(); await p.waitForTimeout(600);
  await p.click('text=我是另一半，用分享碼加入'); await p.waitForTimeout(300);
  await p.fill('#j-code', code); await p.fill('#j-pass', '123456'); await p.fill('#j-name', '小明'); await p.click('#join-btn'); await p.waitForTimeout(1200);
  log('partner tour', await p.isVisible('.tour-dlg'), await p.textContent('.tour-dlg h2').catch(() => ''));
  await p.click('#tour-next'); await p.waitForTimeout(200);
  log('partner p2', await p.textContent('.tour-dlg .muted'));
  await p.screenshot({ path: 'r16-tour-partner.png' });
  await p.click('#tour-skip'); await p.reload(); await p.waitForTimeout(900);
  log('partner not again', !(await p.isVisible('.tour-dlg')));
  console.log('errors', errs); await b.close();
})();
