const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const log = (...a) => console.log(...a); const errs = [];
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => { localStorage.setItem('tourDone', '1'); localStorage.setItem('guestStarted', '1'); localStorage.setItem('a2hsNever', '1'); });
  const p = await ctx.newPage(); p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  const as = async (uid, hash) => { await p.evaluate((u) => (u ? sessionStorage.setItem('mockUid', u) : sessionStorage.removeItem('mockUid')), uid); await p.goto(U + '#/settings'); await p.reload(); await p.waitForTimeout(500); await p.goto(U + hash); await p.reload(); await p.waitForTimeout(900); };
  await p.goto(U + '#/login'); await p.waitForTimeout(500);
  await p.fill('#email', 'jas@x.com'); await p.fill('#password', 'secret123'); await p.click('#login-btn'); await p.waitForTimeout(1200);
  const oid = await p.evaluate(() => sessionStorage.getItem('mockUid'));
  await p.goto(U + '#/settings'); await p.waitForTimeout(700);
  log('nav chips', await p.$$eval('.set-nav .chip', (e) => e.map((x) => x.textContent).join(',')));
  log('first section', await p.$eval('.set-sec', (e) => e.textContent));
  await p.screenshot({ path: 'r26-settings.png' });
  await p.fill('#s-name', 'Jasmine'); await p.fill('#s-pass', '123456'); await p.click('#s-create'); await p.waitForTimeout(800);
  const code = (await p.textContent('.share-code')).trim();
  await p.click('.set-nav [data-jump="set-backup"]'); await p.waitForTimeout(700);
  log('jumped', await p.evaluate(() => Math.round(document.getElementById('set-backup').getBoundingClientRect().top)));
  await as(null, '#/login'); await p.click('text=我是另一半，用分享碼加入'); await p.waitForTimeout(300);
  await p.fill('#j-code', code); await p.fill('#j-pass', '123456'); await p.fill('#j-name', '小明'); await p.click('#join-btn'); await p.waitForTimeout(1200);
  log('partner waiting', (await p.textContent('#app')).includes('同意'));
  await as(oid, '#/');
  log('home join card', await p.isVisible('.join-req'), await p.isVisible('[data-home-approve]'));
  await p.screenshot({ path: 'r27-home-join.png' });
  await p.click('[data-home-approve]'); await p.waitForTimeout(1200);
  log('approved, card gone', !(await p.isVisible('.join-req')));
  console.log('errors', errs); await b.close();
})();
