const { chromium } = require('playwright');
const fs = require('fs');
const U = (process.env.U || 'http://localhost:8770/');
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const errs = [];
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => { localStorage.setItem('tourDone', '1'); localStorage.setItem('a2hsNever', '1'); });
  const p = await ctx.newPage(); p.on('pageerror', (e) => errs.push(e.message));
  await p.goto(U); await p.waitForTimeout(900);
  console.log('top login', await p.isVisible('#home-login'), 'card login', await p.isVisible('#guest-login'), 'card signup', await p.isVisible('#guest-signup'));
  await p.screenshot({ path: (process.env.SHOT_DIR || '.') + '/home-login-entry.png' });
  await p.click('#home-login'); await p.waitForTimeout(600);
  console.log('login page', p.url().endsWith('#/login'), await p.isVisible('#login-btn'), (await p.textContent('#login-btn')).trim());
  await p.goto(U + '#/'); await p.waitForTimeout(600);
  await p.click('#guest-signup'); await p.waitForTimeout(600);
  console.log('signup page', (await p.textContent('#login-btn')).trim());
  console.log('errors', errs); await b.close();
})();
