// #10 離線：service worker 讓 App 沒網路也打得開；雲端模式顯示手機裡最近看過的紀錄，不能新增
const { chromium } = require('playwright');
const fs = require('fs');
const U = process.env.U || 'http://localhost:8770/';
(async () => {
  const b = await chromium.launch(require('./_launch'));
  const errs = [];
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 } });
  await ctx.route('**/vendor/supabase-2.117.2.js', (r) => r.fulfill({ contentType: 'text/javascript', body: fs.readFileSync('mock2.js', 'utf8') }));
  await ctx.addInitScript(() => { localStorage.setItem('tourDone', '1'); localStorage.setItem('a2hsNever', '1'); localStorage.setItem('swTest', '1'); new MutationObserver(() => document.querySelectorAll('.celebrate:not(.wish-dlg):not(.danger-dlg), .tour-dlg').forEach((e) => e.remove())).observe(document, { childList: true, subtree: true }); });
  const p = await ctx.newPage(); p.on('pageerror', (e) => errs.push(e.message)); p.on('dialog', (d) => d.accept());
  await p.goto(U + '#/login'); await p.waitForTimeout(800);
  await p.fill('#email', 'jas@x.com'); await p.fill('#password', 'secret123'); await p.click('#login-btn'); await p.waitForTimeout(1200);
  await p.click('#role-owner'); await p.waitForTimeout(600);
  const add = async (type, title) => { await p.goto(U + '#/new/' + type); await p.waitForTimeout(600); await p.fill('#f-title', title); await p.click('#save'); await p.waitForTimeout(1000); return p.url().split('/').pop(); };
  const a = await add('happy', '離線也看得到');
  await add('cloud', '烏雲一則');
  await p.goto(U + '#/'); await p.waitForTimeout(800);
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(800);
  const swOk = await p.evaluate(async () => { const r = await navigator.serviceWorker.ready; return !!r.active; });
  console.log('sw active', swOk);
  await p.reload(); await p.waitForTimeout(1000);
  console.log('controlled', await p.evaluate(() => !!navigator.serviceWorker.controller));
  await ctx.setOffline(true);
  await p.goto(U + '#/'); await p.reload(); await p.waitForTimeout(1500);
  const home = await p.textContent('#app');
  console.log('offline home loads', home.includes('離線也看得到') || home.includes('美好'), 'bar', await p.isVisible('.offline-bar'));
  await p.screenshot({ path: (process.env.SHOT_DIR || '.') + '/offline-home.png' });
  await p.goto(U + '#/list/happy'); await p.waitForTimeout(1000);
  console.log('offline list', (await p.textContent('#app')).includes('離線也看得到'));
  await p.goto(U + '#/view/' + a); await p.waitForTimeout(1000);
  console.log('offline detail', (await p.textContent('#app')).includes('離線也看得到'));
  await p.goto(U + '#/new/happy'); await p.waitForTimeout(700); await p.fill('#f-title', '離線新增'); await p.click('#save'); await p.waitForTimeout(1000);
  const t = await p.textContent('.toast').catch(() => '');
  console.log('offline save blocked', /離線/.test(t), JSON.stringify(t));
  await ctx.setOffline(false); await p.waitForTimeout(1200);
  console.log('bar gone online', !(await p.isVisible('.offline-bar')));
  await p.goto(U + '#/settings'); await p.waitForTimeout(700);
  await p.click('#logout').catch(() => {}); await p.waitForTimeout(1000);
  console.log('cache cleared on logout', await p.evaluate(() => Object.keys(localStorage).filter((k) => k.startsWith('offline:')).length === 0));
  console.log('errors', errs); await b.close();
})();
